modLoader = "javafml"
loaderVersion = "[${forge_version},)"

issueTrackerURL = ""
license = "CC0-1.0 license"

[[mods]]
modId = "mod_id"
version = "${version}"
displayName = "Mod Name Mod"
credits = ["none"]
authors = "anvian"
description = "Mod description"
logoFile = "icon.png"
displayURL= ""

[[dependencies.mod_id]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mod_id]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mod_id]]
modId="create"
mandatory=true
versionRange="[${create_version},)"
ordering="NONE"
side="BOTH"